language: generic

sudo: required

services:
  - docker

before_install:

  - docker build -t leejs/node-delivery-test ./

script:
  - docker run -e CI=true leejs/node-delivery-test

after_success:

  - docker build -t leejs/node-delivery ./
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push leejs/node-delivery
