language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t leejs/node-delivery ./

script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push leejs/node-delivery

after_success:
 - echo "success"
